apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    tier: platform
spec:
  project: platform
  
  source:
    repoURL: https://gitlab.com/your-org/platform-k8-gitops.git  # Update with your repo URL
    targetRevision: main
    path: argocd/applications
    directory:
      recurse: false
      include: '*-dev.yaml'
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
  
  # Sync waves for ordered deployment
  syncWave: 0
