---
# Patch to add IAM role annotations to AWS Secrets Manager Provider service account
# Apply this after deploying the Helm chart
#
# Usage:
#   kubectl patch sa secrets-store-csi-driver-provider-aws -n kube-system --patch-file k8s-resources/patches/aws-provider-sa-prod.yaml
#
# Or use the script:
#   ./scripts/annotate-aws-provider-sa.sh -e prod -a YOUR_ACCOUNT_ID

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver-provider-aws
  namespace: kube-system
  annotations:
    # IRSA annotation (used when authMethod is "irsa")
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/EKS-SecretsStore-Role-prod"
    # Pod Identity annotation (used when authMethod is "pod-identity")
    eks.amazonaws.com/pod-identity-association-role-arn: "arn:aws:iam::ACCOUNT_ID:role/EKS-SecretsStore-Role-prod"
