resources:
  - ../../base/ingress.yaml
patches:
  - target:
      kind: Ingress
      name: demo-app
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: demo.dev.example.com
