apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-helm-charts-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  
  source:
    repoURL: https://gitlab.com/your-org/platform-k8-gitops.git  # Update with your repo URL
    targetRevision: main
    path: charts
    
    # Helm chart discovery
    directory:
      recurse: true
      include: '*/values-dev.yaml'
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: false  # Set to true for automatic pruning
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences in certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
