---
# Patch to add IAM role annotations to AWS Secrets Manager Provider service account
# Apply this after deploying the Helm chart
#
# Usage:
#   kubectl patch sa csi-secrets-store-provider-aws -n kube-system --patch-file k8s-resources/secrets-store-provider-aws/overlays/dev/serviceaccount-patch.yaml
#
# Or use the script:
#   ./scripts/annotate-aws-provider-sa.sh -e dev -a YOUR_ACCOUNT_ID

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-aws
  namespace: kube-system
  annotations:
    # IRSA annotation (used when authMethod is "irsa")
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/EKS-SecretsStore-Role-dev"
    # Pod Identity annotation (used when authMethod is "pod-identity")
    eks.amazonaws.com/pod-identity-association-role-arn: "arn:aws:iam::ACCOUNT_ID:role/EKS-SecretsStore-Role-dev"
